//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر به کیس دسترسی ندارد.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس پست در دسترس نیست .
        /// </summary>
        public static string AccessDeniedToPostInqueryService {
            get {
                return ResourceManager.GetString("AccessDeniedToPostInqueryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت سرویس توکن پست با خطا مواجه شد.
        /// </summary>
        public static string AccessDeniedToPostTokenService {
            get {
                return ResourceManager.GetString("AccessDeniedToPostTokenService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم دسترسی به سرویس مورد نظر .
        /// </summary>
        public static string AccessDeniedToService {
            get {
                return ResourceManager.GetString("AccessDeniedToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در دریافت اطلاعات رخ داده است.
        /// </summary>
        public static string AnErrorGettingInformation {
            get {
                return ResourceManager.GetString("AnErrorGettingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است.
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اپلیکیشن الزامی است.
        /// </summary>
        public static string ApplicationNameIsRequired {
            get {
                return ResourceManager.GetString("ApplicationNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز موافقت اصولی وجود ندارد.
        /// </summary>
        public static string ApprovallicenseNotExist {
            get {
                return ResourceManager.GetString("ApprovallicenseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام سوابق ورزشکاران.
        /// </summary>
        public static string AthleteInfoInquiry {
            get {
                return ResourceManager.GetString("AthleteInfoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب بانکی یافت نشد.
        /// </summary>
        public static string BankAccountWasNotFound {
            get {
                return ResourceManager.GetString("BankAccountWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک مورد نظر یافت نشد.
        /// </summary>
        public static string BankWasNotFound {
            get {
                return ResourceManager.GetString("BankWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام بیمه ورزشی.
        /// </summary>
        public static string BimehVarzeshiInquiry {
            get {
                return ResourceManager.GetString("BimehVarzeshiInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس کسب و کار یا موقعیت جغرافیایی کسب و کار با فرمت Latitude,Longitude الزامی میباشد.
        /// </summary>
        public static string BusinessInfoAddressIsRequired {
            get {
                return ResourceManager.GetString("BusinessInfoAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن اطلاعات کسب و کار الزامی میباشد.
        /// </summary>
        public static string BusinessInfoIsRequired {
            get {
                return ResourceManager.GetString("BusinessInfoIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف از صدور مجوز.
        /// </summary>
        public static string CancelLicenseIssuance {
            get {
                return ResourceManager.GetString("CancelLicenseIssuance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیس یافت نشد.
        /// </summary>
        public static string CaseNotFound {
            get {
                return ResourceManager.GetString("CaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت احوال.
        /// </summary>
        public static string CheckPersonalInfo {
            get {
                return ResourceManager.GetString("CheckPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام ثبت احوال.
        /// </summary>
        public static string CheckPersonalInfoInquiry {
            get {
                return ResourceManager.GetString("CheckPersonalInfoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه مورد نظر یافت نشد.
        /// </summary>
        public static string ClientSystemWasNotFound {
            get {
                return ResourceManager.GetString("ClientSystemWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام سوابق مربی گری.
        /// </summary>
        public static string CoachCertificationInfoInquiry {
            get {
                return ResourceManager.GetString("CoachCertificationInfoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری را تکمیل کنید.
        /// </summary>
        public static string CompleteUserInformation {
            get {
                return ResourceManager.GetString("CompleteUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیمانکار.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع لینک وارد شده قبلا ثبت شده است.
        /// </summary>
        public static string ContractorLinksTypeDuplicate {
            get {
                return ResourceManager.GetString("ContractorLinksTypeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پیمانکار تکراری است.
        /// </summary>
        public static string ContractorNameDuplicate {
            get {
                return ResourceManager.GetString("ContractorNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیمانکار مورد نظر یافت نشد.
        /// </summary>
        public static string ContractorsNotFound {
            get {
                return ResourceManager.GetString("ContractorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر فایل یافت نشد.
        /// </summary>
        public static string CouldNotFindFilePath {
            get {
                return ResourceManager.GetString("CouldNotFindFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فراخوانی متد ها در روز اخیر.
        /// </summary>
        public static string CountOfMethodsCallInLastDay {
            get {
                return ResourceManager.GetString("CountOfMethodsCallInLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاگین سرویس اقلام داده.
        /// </summary>
        public static string DataItemsLogin {
            get {
                return ResourceManager.GetString("DataItemsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ای یافت نشد.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صحیح وارد نشده است.
        /// </summary>
        public static string DateNotValid {
            get {
                return ResourceManager.GetString("DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرک.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات اجباری است.
        /// </summary>
        public static string DescIsRequired {
            get {
                return ResourceManager.GetString("DescIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اختصاصی ارسال شده به این سرویس دسترسی ندارد.
        /// </summary>
        public static string DoNotAccessYourProviderCode {
            get {
                return ResourceManager.GetString("DoNotAccessYourProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک وارد شده تکراری است.
        /// </summary>
        public static string DuplicateBank {
            get {
                return ResourceManager.GetString("DuplicateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب بانکی تکراری است.
        /// </summary>
        public static string DuplicateBankAccount {
            get {
                return ResourceManager.GetString("DuplicateBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه وارد شده تکراری است.
        /// </summary>
        public static string DuplicateClientSystem {
            get {
                return ResourceManager.GetString("DuplicateClientSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate entry.
        /// </summary>
        public static string DuplicateEntryEn {
            get {
                return ResourceManager.GetString("DuplicateEntryEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان را وارد کنید.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت با شکست مواجه شد.
        /// </summary>
        public static string Error401 {
            get {
                return ResourceManager.GetString("Error401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس استعلام ثبت احوال خطا دارد، لطفا از درگاه دولت من اقدام کنید.
        /// </summary>
        public static string ErrorInquirySabteAhval {
            get {
                return ResourceManager.GetString("ErrorInquirySabteAhval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس مورد نظر قطع است دقایقی دیگر تلاش کنید.
        /// </summary>
        public static string ErrorService {
            get {
                return ResourceManager.GetString("ErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس استعلام شاهکار خطا دارد، لطفا از درگاه دولت من اقدام کنید.
        /// </summary>
        public static string ErrorShahkarService {
            get {
                return ResourceManager.GetString("ErrorShahkarService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس {0} در دسترس نیست لطفا دقایقی دیگر تلاش نمایید.
        /// </summary>
        public static string ExternalServiceOutOfResponse {
            get {
                return ResourceManager.GetString("ExternalServiceOutOfResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های وارد شده تکمیل نمی باشد.
        /// </summary>
        public static string ExtraValueIsRequired {
            get {
                return ResourceManager.GetString("ExtraValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست مورد نظر صحیح نمیباشد،لطفا دوباره از درگاه ملی در خواست دهید.
        /// </summary>
        public static string FailedLicenseResponse {
            get {
                return ResourceManager.GetString("FailedLicenseResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم دریافت پاسخ از درگاه بانک، مجددا تلاش کنید.
        /// </summary>
        public static string FailureToReceiveResponseFromBankPortal {
            get {
                return ResourceManager.GetString("FailureToReceiveResponseFromBankPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فدراسیون.
        /// </summary>
        public static string Federation {
            get {
                return ResourceManager.GetString("Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیدی فایل الزامی است.
        /// </summary>
        public static string FileIDRequired {
            get {
                return ResourceManager.GetString("FileIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل الزامی است.
        /// </summary>
        public static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل یافت نشد.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی مبدا الزامی است.
        /// </summary>
        public static string FromNationalCodeIsRequired {
            get {
                return ResourceManager.GetString("FromNationalCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت G4b.
        /// </summary>
        public static string G4bToken {
            get {
                return ResourceManager.GetString("G4bToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام تطبیق کد ملی و شماره همراه.
        /// </summary>
        public static string GetConfirmServiceId {
            get {
                return ResourceManager.GetString("GetConfirmServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام سرویس کرونا.
        /// </summary>
        public static string GetCoronaDisease {
            get {
                return ResourceManager.GetString("GetCoronaDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام سوابق تحصیلی.
        /// </summary>
        public static string GetEducationDegreeByNationalCode {
            get {
                return ResourceManager.GetString("GetEducationDegreeByNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام از ثبت احوال.
        /// </summary>
        public static string GetInquirySabteAhval {
            get {
                return ResourceManager.GetString("GetInquirySabteAhval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام وضعیت از G4B.
        /// </summary>
        public static string GetLatestG4bStatus {
            get {
                return ResourceManager.GetString("GetLatestG4bStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام اخرین وضعیت.
        /// </summary>
        public static string GetLatestStatus {
            get {
                return ResourceManager.GetString("GetLatestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین وضعیت درخواست مجوز.
        /// </summary>
        public static string GetLatestStatusOfRequestedLicense {
            get {
                return ResourceManager.GetString("GetLatestStatusOfRequestedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین وضعیت درخواست مجوز یکتا.
        /// </summary>
        public static string GetLatestStatusOfRequestedOldLicense {
            get {
                return ResourceManager.GetString("GetLatestStatusOfRequestedOldLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام سوءپیشینه.
        /// </summary>
        public static string GetPoliceClearanceCertificate {
            get {
                return ResourceManager.GetString("GetPoliceClearanceCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پیامک.
        /// </summary>
        public static string GetSMSDeliver {
            get {
                return ResourceManager.GetString("GetSMSDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پیامک بالک.
        /// </summary>
        public static string GetSMSDeliverBulk {
            get {
                return ResourceManager.GetString("GetSMSDeliverBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پیامک های دریافتی.
        /// </summary>
        public static string GetSMSReceiveList {
            get {
                return ResourceManager.GetString("GetSMSReceiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات کاربری.
        /// </summary>
        public static string GetUserInfo {
            get {
                return ResourceManager.GetString("GetUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی کاربر به پرتال.
        /// </summary>
        public static string GivePortalAccessToUser {
            get {
                return ResourceManager.GetString("GivePortalAccessToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت درگاه ملی.
        /// </summary>
        public static string GovToken {
            get {
                return ResourceManager.GetString("GovToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فرد به درجه شهادت نائل شده است.
        /// </summary>
        public static string HeSheIsMartyr {
            get {
                return ResourceManager.GetString("HeSheIsMartyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیرنده سند به درستی وارد نشده است.
        /// </summary>
        public static string IncoorectDocumentRecipientInfo {
            get {
                return ResourceManager.GetString("IncoorectDocumentRecipientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات گیرندگان به درستی وارد نشده است.
        /// </summary>
        public static string IncoorectRecipientsInfo {
            get {
                return ResourceManager.GetString("IncoorectRecipientsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت ارسال پاسخ سند درست وارد نشده است.
        /// </summary>
        public static string IncorrectDeadlineForSendingResponse {
            get {
                return ResourceManager.GetString("IncorrectDeadlineForSendingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس موسس باید از نوع png یا jpg باشد.
        /// </summary>
        public static string IncorrectImageType {
            get {
                return ResourceManager.GetString("IncorrectImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی نوع مجوز درخواستی شما معتبر نمیباشد.
        /// </summary>
        public static string IncorrectLicenseType {
            get {
                return ResourceManager.GetString("IncorrectLicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی یا تاریخ تولد اشتباه است.
        /// </summary>
        public static string IncorrectNationalCodeOrBirthDate {
            get {
                return ResourceManager.GetString("IncorrectNationalCodeOrBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اختصاصی اشتباه است.
        /// </summary>
        public static string IncorrectProviderCode {
            get {
                return ResourceManager.GetString("IncorrectProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ضروری وارد نشده است.
        /// </summary>
        public static string IncorrectRequiredInfo {
            get {
                return ResourceManager.GetString("IncorrectRequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد را وارد کنید.
        /// </summary>
        public static string InputBirthDate {
            get {
                return ResourceManager.GetString("InputBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را وارد کنید.
        /// </summary>
        public static string InputNationalCode {
            get {
                return ResourceManager.GetString("InputNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر های دریافتی دچار مشکل است لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string InputParamsErrors {
            get {
                return ResourceManager.GetString("InputParamsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه را وارد کنید.
        /// </summary>
        public static string InputPhoneNumber {
            get {
                return ResourceManager.GetString("InputPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند فایل نامعتبر است.
        /// </summary>
        public static string InvalidExtensions {
            get {
                return ResourceManager.GetString("InvalidExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی نامعتبر است.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای ورودی صحیح نمی باشد.
        /// </summary>
        public static string InvalidInputParams {
            get {
                return ResourceManager.GetString("InvalidInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک آخرین وضعیت درگاه ملی معتبر نمی باشد.
        /// </summary>
        public static string InvalidLatestStatusLink {
            get {
                return ResourceManager.GetString("InvalidLatestStatusLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نامعتبر است.
        /// </summary>
        public static string InvalidNationalCode {
            get {
                return ResourceManager.GetString("InvalidNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ پرداخت صحیح نمی باشد.
        /// </summary>
        public static string InvalidPaymentAmount {
            get {
                return ResourceManager.GetString("InvalidPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدور.
        /// </summary>
        public static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صدور اجباری است.
        /// </summary>
        public static string IssueDateIsRequired {
            get {
                return ResourceManager.GetString("IssueDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مجوز مورد نظر برای پیمانکار دیگری ثبت شده است.
        /// </summary>
        public static string LicenseCodeAddedOtherContractor {
            get {
                return ResourceManager.GetString("LicenseCodeAddedOtherContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مجوز تکراری است.
        /// </summary>
        public static string LicenseCodeDuplicate {
            get {
                return ResourceManager.GetString("LicenseCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدمجوز مورد نظر قبلا ثبت شده است.
        /// </summary>
        public static string LicenseCodeDuplicateInContractor {
            get {
                return ResourceManager.GetString("LicenseCodeDuplicateInContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مجوز را وارد کنید.
        /// </summary>
        public static string LicenseCodeIsRequired {
            get {
                return ResourceManager.GetString("LicenseCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز مورد نظر یافت نشد.
        /// </summary>
        public static string LicenseCodeNotFound {
            get {
                return ResourceManager.GetString("LicenseCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز کاربر مورد نظر قبلا ابطال شده است.
        /// </summary>
        public static string LicenseHasAlreadyBeenRevoked {
            get {
                return ResourceManager.GetString("LicenseHasAlreadyBeenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز یافت نشد.
        /// </summary>
        public static string LicenseNotFound {
            get {
                return ResourceManager.GetString("LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مجوز نامعتبر است.
        /// </summary>
        public static string LicenseTypeIsNotValid {
            get {
                return ResourceManager.GetString("LicenseTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک وارد شده صحیح نمی باشد.
        /// </summary>
        public static string LinkInvalid {
            get {
                return ResourceManager.GetString("LinkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست متدهایی که بیشترین تعداد فراخوانی داشتن.
        /// </summary>
        public static string ListOfMethodsThatHaveTheMostNumberOfCalls {
            get {
                return ResourceManager.GetString("ListOfMethodsThatHaveTheMostNumberOfCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاگ مورد نظر یافت نشد.
        /// </summary>
        public static string LogNotFound {
            get {
                return ResourceManager.GetString("LogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مگفا.
        /// </summary>
        public static string Magfa {
            get {
                return ResourceManager.GetString("Magfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام قهرمانی ورزشکاران.
        /// </summary>
        public static string MedalInfoInquiry {
            get {
                return ResourceManager.GetString("MedalInfoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیامک الزامی است.
        /// </summary>
        public static string MessageIsRequired {
            get {
                return ResourceManager.GetString("MessageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و ساعت اخرین لاگ متدها.
        /// </summary>
        public static string MethodsLastValuesCreateDate {
            get {
                return ResourceManager.GetString("MethodsLastValuesCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش کد وضعیت متدها.
        /// </summary>
        public static string MethodsReportByStatusCodes {
            get {
                return ResourceManager.GetString("MethodsReportByStatusCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کد ملی به این شماره همراه تعلق ندارد.
        /// </summary>
        public static string MismatchNationalCodeWithPhoneNumber {
            get {
                return ResourceManager.GetString("MismatchNationalCodeWithPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مجوز موافقت اصولی شما بیشتر از یک ماه باقی مانده.
        /// </summary>
        public static string MoreOneMonthsConsentRequestLicense {
            get {
                return ResourceManager.GetString("MoreOneMonthsConsentRequestLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مجوز تشخیص صلاحیت شما بیشتر از دو ماه باقی مانده.
        /// </summary>
        public static string MoreTwoMonthsPersonalVerifyingLicense {
            get {
                return ResourceManager.GetString("MoreTwoMonthsPersonalVerifyingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام را وارد کنید.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانشگاهی یافت نشد.
        /// </summary>
        public static string NoUniversityFound {
            get {
                return ResourceManager.GetString("NoUniversityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز بهره برداری وجود ندارد.
        /// </summary>
        public static string OperationLicenseNotExist {
            get {
                return ResourceManager.GetString("OperationLicenseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت در وضعیت {0} است.
        /// </summary>
        public static string PaymentIsStatus {
            get {
                return ResourceManager.GetString("PaymentIsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت مورد نظر یافت نشد.
        /// </summary>
        public static string PaymentNotFound {
            get {
                return ResourceManager.GetString("PaymentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام اطلاعات عمومی.
        /// </summary>
        public static string PersonalInfoInquiry {
            get {
                return ResourceManager.GetString("PersonalInfoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص مورد نظر فوت کرده است.
        /// </summary>
        public static string PersonIsDead {
            get {
                return ResourceManager.GetString("PersonIsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس داروخانه یافت نشد.
        /// </summary>
        public static string PharmacyLocationNotFounde {
            get {
                return ResourceManager.GetString("PharmacyLocationNotFounde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس نادرست است.
        /// </summary>
        public static string PhoneNumberIsIncorrect {
            get {
                return ResourceManager.GetString("PhoneNumberIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراحل حذف فایل با خطا مواجه شد.
        /// </summary>
        public static string ProcessDeleteFileError {
            get {
                return ResourceManager.GetString("ProcessDeleteFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرایند مورد نظر در نوع کاربری شما یافت نشد.
        /// </summary>
        public static string ProcessNotFoundeInUserType {
            get {
                return ResourceManager.GetString("ProcessNotFoundeInUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراحل آپلود فایل با خطا مواجه شد.
        /// </summary>
        public static string ProcessUploadFileError {
            get {
                return ResourceManager.GetString("ProcessUploadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدرهگیری الزامی است.
        /// </summary>
        public static string RadNumberIsRequired {
            get {
                return ResourceManager.GetString("RadNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دریافت کننده پیامک الزامی است.
        /// </summary>
        public static string ReceiverNumbersIsRequired {
            get {
                return ResourceManager.GetString("ReceiverNumbersIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام سوابق داوری.
        /// </summary>
        public static string RefereeCertificationInfoInquiry {
            get {
                return ResourceManager.GetString("RefereeCertificationInfoInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز مورد نظر به دلیل 24 ساعت رد شده است.
        /// </summary>
        public static string Rejected24HoursLicense {
            get {
                return ResourceManager.GetString("Rejected24HoursLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن دلایل عدم تایید الزامی میباشد.
        /// </summary>
        public static string RejectReasonsIsRequired {
            get {
                return ResourceManager.GetString("RejectReasonsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا صفحه را رفرش کنید.
        /// </summary>
        public static string ReloadPage {
            get {
                return ResourceManager.GetString("ReloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مجوز قبلا تمدید شده است.
        /// </summary>
        public static string RenewedThisLicense {
            get {
                return ResourceManager.GetString("RenewedThisLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body is empty.
        /// </summary>
        public static string RequestBodyIsEmptyEn {
            get {
                return ResourceManager.GetString("RequestBodyIsEmptyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره درخواست یافت نشد.
        /// </summary>
        public static string RequestNumberDocumentNotFound {
            get {
                return ResourceManager.GetString("RequestNumberDocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره درخواست الزامی است.
        /// </summary>
        public static string RequestNumberIsRequired {
            get {
                return ResourceManager.GetString("RequestNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی الزامی است.
        /// </summary>
        public static string RequiredNationalCode {
            get {
                return ResourceManager.GetString("RequiredNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه مجوز یا کدملی الزامی است.
        /// </summary>
        public static string RequiredNationalCodeOrG4bRequestNumber {
            get {
                return ResourceManager.GetString("RequiredNationalCodeOrG4bRequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمدید.
        /// </summary>
        public static string Revival {
            get {
                return ResourceManager.GetString("Revival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این سند صدوری میباشد.
        /// </summary>
        public static string SanadIsIssued {
            get {
                return ResourceManager.GetString("SanadIsIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با دردست داشتن اصل شناسنامه به اداره ثبت احوال محل سکونت مراجعه نمایید.
        /// </summary>
        public static string SanadIsMarked {
            get {
                return ResourceManager.GetString("SanadIsMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز امتیاز گیری یافت نشد.
        /// </summary>
        public static string ScoringLicenseNotFound {
            get {
                return ResourceManager.GetString("ScoringLicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال سند.
        /// </summary>
        public static string SendLetter {
            get {
                return ResourceManager.GetString("SendLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پيامک نظرسنجی.
        /// </summary>
        public static string SendSurveyMessage {
            get {
                return ResourceManager.GetString("SendSurveyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراخوانی سرویس با خطا مواجه شد، دوباره تلاش کنید.
        /// </summary>
        public static string ServiceCallIsFailed {
            get {
                return ResourceManager.GetString("ServiceCallIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیامک.
        /// </summary>
        public static string SmsSend {
            get {
                return ResourceManager.GetString("SmsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته های مجوز یافت نشد.
        /// </summary>
        public static string SportFieldsNotFound {
            get {
                return ResourceManager.GetString("SportFieldsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان شروع فرایند فقط توسط مسئول {0} امکان پذیر است.
        /// </summary>
        public static string StartingProcessOnlyResponsible {
            get {
                return ResourceManager.GetString("StartingProcessOnlyResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نتیجه نهایی صدور مجوز.
        /// </summary>
        public static string SubmitLicenseIssuanceFinalResult {
            get {
                return ResourceManager.GetString("SubmitLicenseIssuanceFinalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست با موفقیت ثبت شد.
        /// </summary>
        public static string SuccessRequestMessage {
            get {
                return ResourceManager.GetString("SuccessRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعلیق مجوز صادر شده توسط درگاه تخصصی.
        /// </summary>
        public static string SuspendLicense {
            get {
                return ResourceManager.GetString("SuspendLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل نمیتواند بیشتر از {0} باشد.
        /// </summary>
        public static string TheFileSizeCannotBeExceeded {
            get {
                return ResourceManager.GetString("TheFileSizeCannotBeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایپ فایل باید از نوع {0} باشد.
        /// </summary>
        public static string TheFileTypeIsNotCorrect {
            get {
                return ResourceManager.GetString("TheFileTypeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست های صدور باشگاه های ورزشی.
        /// </summary>
        public static string TheNumberOfClubIssuanceRequests {
            get {
                return ResourceManager.GetString("TheNumberOfClubIssuanceRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کنسلی های 24 ساعته اعلام نشده.
        /// </summary>
        public static string TheNumberOfMissed24 {
            get {
                return ResourceManager.GetString("TheNumberOfMissed24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست های یکتا.
        /// </summary>
        public static string TheNumberOfUniqueRequests {
            get {
                return ResourceManager.GetString("TheNumberOfUniqueRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فراخوانی های ناموفق ارسال اطلاعات متقاضی.
        /// </summary>
        public static string TheNumberOfUnsuccessfulCallsSendApplicantInfo {
            get {
                return ResourceManager.GetString("TheNumberOfUnsuccessfulCallsSendApplicantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست های با زمین.
        /// </summary>
        public static string TheNumberOfWithLandRequests {
            get {
                return ResourceManager.GetString("TheNumberOfWithLandRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست های بدون زمین.
        /// </summary>
        public static string TheNumberOfWithoutLandRequests {
            get {
                return ResourceManager.GetString("TheNumberOfWithoutLandRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder has been stored successfully.
        /// </summary>
        public static string TheReminderHasBeenStoredSuccessfullyEn {
            get {
                return ResourceManager.GetString("TheReminderHasBeenStoredSuccessfullyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been stored successfully.
        /// </summary>
        public static string TheRequestHasBeenStoredSuccessfullyEn {
            get {
                return ResourceManager.GetString("TheRequestHasBeenStoredSuccessfullyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند مورد نظر پرداخت شده است.
        /// </summary>
        public static string ThisItemAlreadyIsPaied {
            get {
                return ResourceManager.GetString("ThisItemAlreadyIsPaied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ارسال یا دریافت اطلاعات بیش از حد طولانی شده است.
        /// </summary>
        public static string TimeoutOccured {
            get {
                return ResourceManager.GetString("TimeoutOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی مقصد الزامی است.
        /// </summary>
        public static string ToNationalCodeIsRequired {
            get {
                return ResourceManager.GetString("ToNationalCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکتا.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نتیجه نهایی شناسه یکتا.
        /// </summary>
        public static string UniqueIdProcessResult {
            get {
                return ResourceManager.GetString("UniqueIdProcessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام از ثبت احوال موفقیت آمیز نبود.
        /// </summary>
        public static string UnSuccessInquirySabteAhval {
            get {
                return ResourceManager.GetString("UnSuccessInquirySabteAhval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع تعلیق مجوز تعلیق شده توسط درگاه تخصصی.
        /// </summary>
        public static string UnSuspendLicense {
            get {
                return ResourceManager.GetString("UnSuspendLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه وارد شده دارای مجوز معتبر نمی باشد.
        /// </summary>
        public static string UserHasNoValidLicense {
            get {
                return ResourceManager.GetString("UserHasNoValidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر دارای فرایند باز می باشد.
        /// </summary>
        public static string UserHasOpenProcess {
            get {
                return ResourceManager.GetString("UserHasOpenProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت وزارت.
        /// </summary>
        public static string VezaratToken {
            get {
                return ResourceManager.GetString("VezaratToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به مجوز دسترسی ندارید.
        /// </summary>
        public static string YouDoNotHaveAccessToLicense {
            get {
                return ResourceManager.GetString("YouDoNotHaveAccessToLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر دارای مجوز موافقت اصولی نیست.
        /// </summary>
        public static string YouDoNotHaveConstRequestLicense {
            get {
                return ResourceManager.GetString("YouDoNotHaveConstRequestLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز بهره برداری گروهی نمی باشید.
        /// </summary>
        public static string YouDoNotHaveGroupOperationLicense {
            get {
                return ResourceManager.GetString("YouDoNotHaveGroupOperationLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز بهره برداری انجمن نمی باشید.
        /// </summary>
        public static string YouDoNotHaveOperationLicenseOfAssociations {
            get {
                return ResourceManager.GetString("YouDoNotHaveOperationLicenseOfAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز بهره برداری بیمارستان نمی باشید.
        /// </summary>
        public static string YouDoNotHaveOperationLicenseOfHospital {
            get {
                return ResourceManager.GetString("YouDoNotHaveOperationLicenseOfHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز بهره برداری شخصی نمی باشید.
        /// </summary>
        public static string YouDoNotHavePersonalOperationLicense {
            get {
                return ResourceManager.GetString("YouDoNotHavePersonalOperationLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز تشخیص صلاحیت نمی باشید.
        /// </summary>
        public static string YouDoNotHavePersonalVerifyingLicense {
            get {
                return ResourceManager.GetString("YouDoNotHavePersonalVerifyingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز مورد نظر می باشید.
        /// </summary>
        public static string YouHaveLicense {
            get {
                return ResourceManager.GetString("YouHaveLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دارای مجوز تشخیص صلاحیت می باشید.
        /// </summary>
        public static string YouHavePersonalVerifyingLicense {
            get {
                return ResourceManager.GetString("YouHavePersonalVerifyingLicense", resourceCulture);
            }
        }
    }
}
